const buttonVariants = {
  primary: 'bg-primary text-white border border-primary hover:bg-primary-hover active:bg-primary-pressed',
  primaryGhost: 'bg-transparent text-primary border border-primary hover:bg-primary-hover/10 active:bg-primary-pressed/20',
  primaryOutlined: 'bg-transparent text-primary border border-primary hover:bg-primary-hover/10 active:bg-primary-pressed/20',
  secondary: 'bg-secondary text-text-inverted border border-secondary hover:bg-secondary-hover active:bg-secondary-pressed',
  secondaryGhost: 'bg-transparent text-secondary border border-secondary hover:bg-secondary-hover/10 active:bg-secondary-pressed/20',
  secondaryOutlined: 'bg-transparent text-secondary border border-secondary hover:bg-secondary-hover/10 active:bg-secondary-pressed/20',
   critical: 'bg-critical text-white border border-critical hover:bg-critical-hover active:bg-critical-pressed',
    criticalGhost: 'bg-transparent text-critical border border-critical hover:bg-critical-hover/10 active:bg-critical-pressed/20',
    criticalOutlined: 'bg-transparent text-critical border border-critical hover:bg-critical-hover/10 active:bg-critical-pressed/20',
    high: 'bg-high text-white border border-high hover:bg-high-hover active:bg-high-pressed',
    highGhost: 'bg-transparent text-high border border-high hover:bg-high-hover/10 active:bg-high-pressed/20',
    highOutlined: 'bg-transparent text-high border border-high hover:bg-high-hover/10 active:bg-high-pressed/20',
    medium: 'bg-medium text-white border border-medium hover:bg-medium-hover active:bg-medium-pressed',
    mediumGhost: 'bg-transparent text-medium border border-medium hover:bg-medium-hover/10 active:bg-medium-pressed/20',
    mediumOutlined: 'bg-transparent text-medium border border-medium hover:bg-medium-hover/10 active:bg-medium-pressed/20',
    low: 'bg-low text-white border border-low hover:bg-low-hover active:bg-low-pressed',
    lowGhost: 'bg-transparent text-low border border-low hover:bg-low-hover/10 active:bg-low-pressed/20',
    lowOutlined: 'bg-transparent text-low border border-low hover:bg-low-hover/10 active:bg-low-pressed/20',
    success: 'bg-success text-white border border-success hover:bg-success-hover active:bg-success-pressed',
    successGhost: 'bg-transparent text-success border border-success hover:bg-success-hover/10 active:bg-success-pressed/20',
    successOutlined: 'bg-transparent text-success border border-success hover:bg-success-hover/10 active:bg-success-pressed/20',
    warning: 'bg-warning text-white border border-warning hover:bg-warning-hover active:bg-warning-pressed',
    warningGhost: 'bg-transparent text-warning border border-warning hover:bg-warning-hover/10 active:bg-warning-pressed/20',
    warningOutlined: 'bg-transparent text-warning border border-warning hover:bg-warning-hover/10 active:bg-warning-pressed/20',
    info: 'bg-info text-white border border-info hover:bg-info-hover active:bg-info-pressed',
    infoGhost: 'bg-transparent text-info border border-info hover:bg-info-hover/10 active:bg-info-pressed/20',
    infoOutlined: 'bg-transparent text-info border border-info hover:bg-info-hover/10 active:bg-info-pressed/20',
    error: 'bg-error text-white border border-error hover:bg-error-hover active:bg-error-pressed',
    errorGhost: 'bg-transparent text-error border border-error hover:bg-error-hover/10 active:bg-error-pressed/20',
    errorOutlined: 'bg-transparent text-error border border-error hover:bg-error-hover/10 active:bg-error-pressed/20',
    performance: 'bg-performance text-white border border-performance hover:bg-performance-hover active:bg-performance-pressed',
    performanceGhost: 'bg-transparent text-performance border border-performance hover:bg-performance-hover/10 active:bg-performance-pressed/20',
    performanceOutlined: 'bg-transparent text-performance border border-performance hover:bg-performance-hover/10 active:bg-performance-pressed/20',
    quality: 'bg-quality text-white border border-quality hover:bg-quality-hover active:bg-quality-pressed',
    qualityGhost: 'bg-transparent text-quality border border-quality hover:bg-quality-hover/10 active:bg-quality-pressed/20',
    qualityOutlined: 'bg-transparent text-quality border border-quality hover:bg-quality-hover/10 active:bg-quality-pressed/20',    
    security: 'bg-security text-white border border-security hover:bg-security-hover active:bg-security-pressed',
    securityGhost: 'bg-transparent text-security border border-security hover:bg-security-hover/10 active:bg-security-pressed/20',
    securityOutlined: 'bg-transparent text-security border border-security hover:bg-security-hover/10 active:bg-security-pressed/20',

};

export default buttonVariants;